# Generated by Django 2.2 on 2020-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20200418_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
    ]
